apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: lets-encrypt

spec:
  acme:                                                        
    server: https://acme-v02.api.letsencrypt.org/directory     
    email: thiago@anselme.com.br                                
    privateKeySecretRef:
      name: lets-encrypt-certificate                            
    solvers:
    - http01:
        ingress:
          class: nginx                                            


# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml  