{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: {{ .Release.Name }}-lets-encrypt

spec:
  acme:                                                        
    server: {{ .Values.tls.server }}
    email:  {{ .Values.tls.email }}                              
    privateKeySecretRef:
      name: lets-encrypt-certificate                            
    solvers:
    - http01:
        ingress:
          class: nginx                                            
{{ end }}