apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wordpress-configmap
data:
  WORDPRESS_DB_HOST: {{ .Release.Name }}-svc-mysql
  WORDPRESS_DB_NAME: {{ .Values.wordpress.database.wordpress_db_name }}