apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-wordpress
  labels:
    {{ range $key, $val := .Values.wordpress.labels }}
      {{ $key }}: {{ $val }}
    {{ end }}   

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: wordpress-mainapp
  {{ if not .Values.wordpress.autoscalling.enabled }}
  replicas: 1
  {{ end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wordpress-mainapp
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.1-apache

          resources:
            limits:
              memory: {{ .Values.wordpress.resources.memory_limit }}
              cpu: {{ .Values.wordpress.resources.cpu_limit }}
            requests:
              memory: {{ .Values.wordpress.resources.memory_requested }}
              cpu: {{ .Values.wordpress.resources.cpu_requested }}           

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-wordpress-configmap
            - secretRef:
                name: {{ .Release.Name }}-wordpress-secret
          
          startupProbe:                 # Estrutura para start apenas desse container. O que parece razoável? Se o banco estiver no ar ok ,mas se não, pode ter que esperar um pouco. Para o start tudo bem.
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

          readinessProbe:               # Essa é a reação mais rápida a falhas. O tráfego é redirecionado. Provavelmente a falha é externa.
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 1

          livenessProbe:                # Essa é a reação mais lenta, gerando reboot da maquina. Isso considera que a falha é interna. 
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 20
            periodSeconds: 60
            failureThreshold: 1            



