# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
  namespace: app-wordpress  
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---
# Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: google-pvc
  namespace: app-wordpress  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: google-storage

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: app-wordpress

  labels:
    # Recomendações da kubernets (https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-general
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm

    # Outros labels comuns
    enviroment: production
    confidenciality: restrict
    compliance: none


spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"              

        envFrom:
          - configMapRef:
              name: mysql
          - secretRef:
              name: mysql
        volumeMounts:
          - mountPath: /var/lib/mysql2
            name: mysql-volume-claim
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 15
          

        readinessProbe:
          tcpSocket:
            port: 3306
          timeoutSeconds: 5
          periodSeconds: 30

        livenessProbe:
          tcpSocket:
            port: 3306
          timeoutSeconds: 10
          periodSeconds: 60         


      volumes:
      - name: mysql-volume-claim
        persistentVolumeClaim:
          claimName: google-pvc
# 