{{ if .Values.mysql.autoscalling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa-mysql
  namespace: app-wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet             # a quem esse destina esse HPA
    name: wordpress
  minReplicas: {{ .Values.mysql.autoscalling.min_replicas }}                  # mínimo de réplicas. O adequado é 2 ou 3
  maxReplicas: {{ .Values.mysql.autoscalling.max_replicas }}                 # máximo de répllicas. Não existe limite adequad
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
  metrics:                       # Qual métrica será utilizada?
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.mysql.autoscalling.avg_cpu_utilization }}  # Consumo acim de 15% de CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.mysql.autoscalling.avg_memory_utilization }}   # Consumo acim de 15% de CPU        
{{ end }}