apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.database.username }}
  MYSQL_PASSWORD:  {{ .Values.mysql.database.username_password   }}
  MYSQL_ROOT_PASSWORD:  {{ .Values.mysql.database.root_password   }}