apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-mysql
spec:
  #type:        # O headless service não possui type definido
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    
